#!/bin/bash
FILES_TO_LINK=(.scripts .ripgreprc)

cd $(dirname -- "$0")
DIR="$(pwd)"

Help() {
  echo "Installs and configures the dotfiles, as seen in README.md"
  echo ""
  echo "Usage: $0"
  echo "options:"
  echo "  -h, --help                    displays this message"
  exit $1
}

for arg in "$@"; do
  case $arg in
    -h|--help)
    Help 0
    ;;
  esac
done

[[ ! -d "$HOME/.backups" ]] && mkdir -p "$HOME/.backups"
for file in ${FILES_TO_LINK[@]}; do
  [[ -e "$HOME/$file" ]] && mv "$HOME/$file" "$HOME/.backups/"
  ln -s "$DIR/$file" "$HOME/"
done

# Installing nix
if ! command -v nix-env > /dev/null; then
  bash <(curl -L https://nixos.org/nix/install)
  if [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
    . "$HOME/.nix-profile/etc/profile.d/nix.sh"
  fi
fi

# Installing Home Manager
if ! command -v home-manager > /dev/null; then
  nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
  nix-channel --update
  nix-shell '<home-manager>' -A install
fi

ln -s "$DIR/nixpkgs" "$HOME/.config/nixpkgs"

home-manager switch

if [[ ! $SHELL =~ "zsh$" ]]; then
  echo "$HOME/.nix-profile/bin/zsh" | sudo tee -a /etc/shells
  chsh $USER -s "$HOME/.nix-profile/bin/zsh"
fi

echo "Finished; you may have to reopen the shell, or source .zshrc again"
