#!/bin/bash
FILES_TO_LINK=(.tool-versions .scripts .ripgreprc .config/nixpkgs .config/git/.gitignore.global)

cd $(dirname -- "$0")
DIR="$(pwd)"

Help() {
  echo "Installs and configures the dotfiles, as seen in README.md"
  echo ""
  echo "Usage: $0"
  echo "options:"
  echo "  -h, --help                    displays this message"
  exit $1
}

for arg in "$@"; do
  case $arg in
    -h|--help)
    Help 0
    ;;
  esac
done

[[ ! -d "$HOME/.backups" ]] && mkdir -p "$HOME/.backups"
for file in ${FILES_TO_LINK[@]}; do
  [[ -e "$HOME/$file" ]] && mv "$HOME/$file" "$HOME/.backups/"
  ln -s "$DIR/$file" "$HOME/$file"
done

# Installing nix
if ! command -v nix-env > /dev/null; then
  unameOut="$(uname -s)"
  case "${unameOut}" in
    Darwin*) bash <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume;;
    *)       bash <(curl -L https://nixos.org/nix/install)
  esac
  if [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
    . "$HOME/.nix-profile/etc/profile.d/nix.sh"
  fi
fi

# Installing Home Manager
if ! command -v home-manager > /dev/null; then
  nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
  nix-channel --update
  nix-shell '<home-manager>' -A install
fi

# Linking local.nix
cp .config/nixpkgs/local.template.nix $HOME/local.nix
ln -s $HOME/local.nix .config/nixpkgs/local.nix

home-manager switch

if [[ ! $SHELL =~ "zsh$" ]]; then
  [[ ! $(grep "$HOME/.nix-profile/bin/zsh" /etc/shells) ]] && echo "$HOME/.nix-profile/bin/zsh" | sudo tee -a /etc/shells
  chsh $USER -s "$HOME/.nix-profile/bin/zsh"
fi

# Installing asdf
if ! command -v asdf > /dev/null; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.0
fi

# Installing asdf languages
asdf install

# Installing Dracula ZSH theme
git clone https://github.com/dracula/zsh.git .dracula/zsh
ln -s $DIR/.dracula/zsh/dracula.zsh-theme $HOME/.oh-my-zsh/themes/dracula.zsh-theme

# Installing Dracula Sublime theme (for bat)
mkdir -p $HOME/.bat-themes
git clone https://github.com/dracula/sublime.git .dracula/sublime
ln -s $DIR/.dracula/sublime/Dracula.tmTheme $HOME/.bat-themes/Dracula.tmTheme


echo "Finished; you may have to reopen the shell, or source .zshrc again"
