version: "3.8"

services:
  jdt:
    image: kaylebor/eclipse.jdt.ls:latest
    network_mode: host
  
  jellyfin:
    image: jellyfin/jellyfin:nightly
    network_mode: host
    user: 1000:1000
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /home/media:/media

volumes:
  jellyfin-config:
  jellyfin-cache: